$pdflatex = "xelatex -synctex=1 -interaction=nonstopmode";
$pdf_previewer = 'start okular';
$pdf_mode = 1;  # output pdf
$out_dir = "build";
$cleanup_mode = 0;
$preview_continuous_mode = 1;
# @default_files = ('main.tex');
