" change leader
let mapleader = ' '

syntax on

" install Vundle bundles
if filereadable(expand("~/.vimrc.plugins"))
  source ~/.vimrc.plugins
endif

" ############## General Settings ##################
set history=2000

filetype on
filetype indent on
filetype plugin on

set autoread          " auto reload the file when the file is modified
set shortmess=atI       " start-up information

set nocompatible
set backup
set backupext=.bak
set backupdir=$HOME/.vim/files/backup
set directory   =$HOME/.vim/files/swap/
set viminfo='100,n$HOME/.vim/files/info/viminfo
set undofile                " So is persistent undo ...
set undodir=$HOME/.vim/files/undo
set undolevels=1000         " How many undos
set undoreload=10000        " number of lines to save for undo
set wildmenu
set wildignore+=*.swp,*.bak,*.pyc,*.class,*.svn,*.tf,*.mdb,*.t7,*.o,*.so,*.npy
set clipboard^=unnamedplus      " use + register for usual operation

" No annoying sound on errors
set title                " change the terminal's title
set novisualbell         " don't beep
set noerrorbells         " don't beep
set tm=500

" For regular expressions turn magic on
set magic

" Configure backspace so it acts as it should act
set backspace=eol,start,indent
set whichwrap+=<,>,h,l

" ################# Display Settings ##################
" general
set ruler
set showcmd
set showmode
set number
set nowrap
set scrolloff=5 " when scroll the screen, the lines remain to show

" command line's height
set statusline=%<%f\ %h%m%r%=%k[%{(&fenc==\"\")?&enc:&fenc}%{(&bomb?\",BOM\":\"\")}]\ %-14.(%l,%c%V%)\ %P
set laststatus=2 " Always show the status line - use 2 lines for the status bar

" match
set showmatch
set matchtime=2 " How many tenths of a second to blink when matching brackets

" search
set hlsearch
set incsearch
set ignorecase
set smartcase     " ignore case if search pattern is all lowercase, case-sensitive otherwise

" folding
set foldenable
set foldmethod=indent

" tab
set tabstop=4
set shiftwidth=4
set softtabstop=4
set smarttab      " insert tabs on the start of a line according to shiftwidth, not tabstop
set expandtab     " convert Tab into space    [for true Tab, Ctrl+V + Tab]
set shiftround    " use multiple of shiftwidth when indenting with '<' and '>'

" use decimal
set nrformats=

" https://stackoverflow.com/questions/3712725/can-i-change-vim-completion-preview-window-height
set previewheight=8
au BufEnter ?* call PreviewHeightWorkAround()
func PreviewHeightWorkAround()
    if &previewwindow
        exec 'setlocal winheight='.&previewheight
    endif
endfunc

" theme
" set background=dark
colorscheme gruvbox

" visual enhance
" set cursorcolumn
set cursorline
" set mousehide               " Hide the mouse cursor while typing

let &colorcolumn=join(range(81,999),",")
highlight ColorColumn ctermbg=235 guibg=#fbf0c1
let &colorcolumn="80,".join(range(120,999),",")

" for error highlight
highlight clear SpellBad
highlight SpellBad term=standout ctermfg=1 term=underline cterm=underline
highlight clear SpellCap
highlight SpellCap term=underline cterm=underline
highlight clear SpellRare
highlight SpellRare term=underline cterm=underline
highlight clear SpellLocal
highlight SpellLocal term=underline cterm=underline

" set some keyword to highlight
if has("autocmd")
  " Highlight TODO, FIXME, NOTE, BUG etc.
  if v:version > 701
    autocmd Syntax * call matchadd('Todo',  '\W\zs\(TODO\|CHANGED\|DONE\|XXX\|HACK\)')
    autocmd Syntax * call matchadd('Debug', '\W\zs\(NOTE\|INFO\|IDEA\|NOTICE\|FIXME\|BUG\)')
  endif
endif


" ################### FileEncode Settings #################
set encoding=utf-8
set fileencodings=ucs-bom,utf-8,cp936,gb18030,big5,euc-jp,euc-kr,latin1
set helplang=cn
set termencoding=utf-8

" Use Unix as the standard file type
set ffs=unix,dos,mac

set formatoptions+=m
set formatoptions+=B " do not add space when merge two chinese line


" ################# others ##################
" autocmd! bufwritepost .vimrc source % " vimrc reload if modified

" auto complete
" refer to VimTip1228
set completeopt=longest,menu

" auto close preview window when leaving insert mode
autocmd InsertLeave * if pumvisible() == 0|pclose|endif

" if this not work ,make sure .viminfo is writable for you
if has("autocmd")
  au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
endif


" ###################### HotKey Settings ##########################

inoremap <C-k> <Up>
inoremap <C-j> <Down>
inoremap <C-h> <Left>
inoremap <C-l> <Right>

"Smart way to move between windows
nnoremap <C-j> <C-W>j
nnoremap <C-k> <C-W>k
nnoremap <C-h> <C-W>h
nnoremap <C-l> <C-W>l

"Reselect visual block after indent/outdent.
vnoremap < <gv
vnoremap > >gv

" auto jump to end of select
" vnoremap <silent> y y`]
" vnoremap <silent> p p`]
" nnoremap <silent> p p`]


" #################### FileType Settings #########################

autocmd FileType python set tabstop=4 shiftwidth=4 expandtab ai
autocmd FileType cuda set ft=cuda.cpp
autocmd FileType ruby set tabstop=2 shiftwidth=2 softtabstop=2 expandtab ai echo hi
autocmd filetype tex,text,markdown set wrap


" ####################### Environment-dependent Settings ############################

" Set extra options when running in GUI mode
if has("gui_running")
    set guifont=Monaco:h12
    set guioptions-=T
    set guioptions+=e
    set guioptions-=r
    set guioptions-=L
    set guitablabel=%M\ %t
    set showtabline=1
    set linespace=2
    set noimd
    set t_Co=256
endif

" nvim related
if has('nvim')
    set termguicolors
    set guicursor=n-v-c:block-Cursor/lCursor-blinkon0,i-ci:ver25-Cursor/lCursor,r-cr:hor20-Cursor/lCursor
    au VimLeave * set guicursor=a:block-blinkon0
end
